### ISSUE TITLE
Languages Missing

### ISSUE THREAD

**Issue by mattevolve** [inpsyde/multilingual-press#136] opened 2015-07-17 14:40 UTC
I'm having the same issue as raised in this previous issue: https://github.com/inpsyde/multilingual-press/issues/126

It appears that the language files fail to load or be installed. A consistent message of

```No items found. We recommend to reinstall this plugin```

is displayed.

Unfortunately, reinstalling doesn't fix the problem.

Commit: 5a2620f94b
Wordpress Version: 4.2.2

**Comment by bueltge** [comment] 2015-07-17 17:54
Thanks. Do you have check this with last version of the master branch?

**Comment by mattevolve** [comment] 2015-07-20 09:22
Yes, I was using the last version (2.2.0)

**Comment by tfrommen** [comment] 2015-08-20 09:51
Unfortunately, we're unable to reproduce this. Can you provide a little more context?

Have the tables (or in this particular case: the `*_mlp_languages` table) successfully been created? Anything else strange?

**Comment by tfrommen** [comment] 2015-09-03 17:53
Closed as _cannot reproduce_.

**Closed by tfrommen** 2015-09-03 17:53 UTC
Labels: bug, cannot reproduce, language manager, needs confirmation

**Comment by drbloom** [comment] 2016-08-24 19:50
I'm seeing the same problem in Version 2.4.7 running WP-Multisite and [Project Nami](http://projectnami.org/).
Is there a problem creating MSSQL tables?

Here is my /LogFiles/php_errors.log
To make the snippet shorter, I removed some language names.

```
[24-Aug-2016 16:29:01 UTC] WordPress database error [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near 'OFFSET'. Code - 102 for query SELECT * FROM wp_blogs WHERE 1=1 AND site_id IN (1) OFFSET 0 ROWS FETCH NEXT 100 ROWS ONLY made by require_once('D:\home\site\wwwroot\wp-admin\network\admin.php'), require_once('D:\home\site\wwwroot\wp-admin\admin.php'), require_once('D:\home\site\wwwroot\wp-load.php'), require_once('D:\home\site\wwwroot\wp-config.php'), require_once('D:\home\site\wwwroot\wp-settings.php'), do_action('plugins_loaded'), call_user_func_array, mlp_init, mlp_pre_run_test, Mlp_Update_Plugin_Data->__construct, wp_get_sites
2016-08-24 16:29:02 Error Code: 515 -- Query NOT translated due to non-defined error code.
INSERT INTO wp_mlp_languages (english_name,native_name,is_rtl,iso_639_1,iso_639_2,wp_locale,http_name,priority) VALUES ( 'Afar', 'Afaraf', '0', 'aa', 'aar', '', 'aa', '1' ),( 'Avestan', 'avesta', '0', 'ae', 'ave', '', 'ae', '1' ),( 'Afrikaans', 'Afrikaans', '0', 'af', 'afr', 'af', 'af-ZA', '1' ),( 'Akan', 'Akan', '0', 'ak', 'aka', 'ak', 'ak', '1' ),( 'Amharic', 'አማርኛ', '0', 'am', 'amh', '', 'am', '1' ),...,( 'Chinese (Taiwan)', '中文', '0', 'zh', 'zho', 'zh_TW', 'zh-TW', '1' ),( 'Chinese', '中文', '0', 'zh', 'zho', '', 'zh', '1' );
```

**Comment by tfrommen** [comment] 2016-08-30 07:10
@drbloom could you please open this as new issue? I will have a look at it next week. Thanks!
