### ISSUE TITLE
Coping from article source does not work anymore - depends on size

### ISSUE THREAD

**Issue by konus1** [inpsyde/multilingual-press#214] opened 2016-05-17 14:33 UTC
#### Version Information
* WordPress: 4.5.2 
* MultilingualPress: 2.4.3

#### Steps to Reproduce
1. create a article more than 3901 characters long.
2. Use the button "quellbeitrag kopieren" (copy source article) in the translation area in dashboard of exisiting article
3. translation area on dashboard turns grey and nothing is copied

#### Full Description
Hello, after the new Version 2.4 on _most_ of my existing (published) articles I am not able to copy the source article text to the translation area any more. There is no error log in the browser console.

I think it is a **size issue** of the source text. If the source article contain more the 3901 characters (including all spaces and cr) the copy command is not successful any more.

![2016-05-17 16-24-42_beitrag bearbeiten beta-dresden fur kinder wordpress](https://cloud.githubusercontent.com/assets/2836147/15325921/52efd7a4-1c4c-11e6-83a2-1f3af6c19567.png)

**Comment by tfrommen** [comment] 2016-05-17 14:55
I cannot reproduce this.

I created a new post, pasted 3901 `1`s into its content, saved the post, and copying the content via the _Copy source post_ button works without a problem. Even twice the amount does.

I tested this both with `SCRIPT_DEBUG` turned on and off, just beacause this led to JavaScript misbehavior some days ago.

Can you provide more information on this?
Can you disable allother plugins, and use a default theme?
Anything else?

**Comment by konus1** [comment] 2016-05-17 21:32
I can reproduce it even with all other plugins turned off and with Twenty Sixteen default theme. After entering more than 3880 .... 3949 characters (depending of title length), with or without saving - the copy source post button does not work any more. Strange.

I am on PHP Version 7.0.6 at the moment and use Firefox 46.0.1 or Chrome Version 50.0.2661.102 m 
I switched from http to https at the same time of the update.

I tested it with wp_debug true and false, but did not find a difference.

I have no other idea what could help to solve the puzzle.

**Comment by konus1** [comment] 2016-05-26 22:27
My problem still exists. You can I help to find the bug?

**Comment by tfrommen** [comment] 2016-06-09 06:38
Sorry, we discussed this (more than once), but cannot reproduce this.

- Default theme, and no other plugins active - but it's still wrong.
- Multiple browsers - in none it's right.
- Switched from http to https, but everything (besides the _Copy source post_ functionality) is working totally fine...
- Debug and no-debug - no difference.

Is this correct so far?

Can you please summarize (again) what you do exactly?

- WordPress 4.5.2
- MultilingualPress 2.4.3
- Create a post (does the post type matter?).
- Click the _Copy stouce post_ button.
- Meta box fades out...
- ...and that's it. Right?

Do you have any MU plugins installed?

Copying the data is done through AJAX. What do your browser dev tools tell you about the request and response?

How did you come up with the _size_ idea in the first place?
Did you try on a post with a lot of content, it didn't work, and then you removed some of the content, which made it work again...? Or is it just that with _most_ longer posts this isn't working (anymore), while short posts always seem to work...?

**Comment by Chrico** [comment] 2016-06-09 06:56
Howdy,

it seems this issue is related to the Apache configuration `LimitRequestLine` [1] which limits the size of GET-parameters. 

CopyPost uses from Backbone `this.model.fetch()` [2] which does a GET-Request. 

## Solution
Since we're sending data in CopyPost to the backend, it would be better to use `this.model.save()` which does a POST-Request.

## Links
[1] http://httpd.apache.org/docs/2.2/mod/core.html#limitrequestline
[2] https://github.com/inpsyde/multilingual-press/blob/492770b02995c3ba6d07fdf098586ac6d61fc485/resources/js/admin/post-translation/CopyPost.js#L144

**Comment by konus1** [comment] 2016-06-09 12:22
@Chrico  I tested your solution and it looks like you solved the problem. Many thanks!
@tfrommen  Please inform me, if you still need all the information.

Yeah, I think this can be closed now!

**Comment by dnaber-de** [comment] 2016-06-09 12:46
No, I think we should fix that in the code. So please leave it open for now.

**Comment by tfrommen** [comment] 2016-06-09 13:22
Hi @konus1,

we may have (found and) fixed this, finally. :)

Please have a look at [the new branch](https://github.com/inpsyde/multilingual-press/tree/issue/214_copy_source_post). Does this (still) work for you?

Kind regards,
Thorsten

**Comment by tfrommen** [comment] 2016-06-14 06:44
Hi @konus1,

did you have a chance to check out [the according branch](https://github.com/inpsyde/multilingual-press/tree/issue/214_copy_source_post). Does this work for you?

Kind regards,
Thorsten

**Comment by konus1** [comment] 2016-06-14 14:11
Yes I tested it and can confirm, it is also working with the linked branch

**Comment by tfrommen** [comment] 2016-06-27 05:49
Fixed in https://github.com/inpsyde/multilingual-press/commit/214b8ef6d57beab42a2587a837feb4ffb6ff4dd5.

**Closed by tfrommen** 2016-06-27 05:49 UTC
Labels: bug, javascript, post translation
