### ISSUE TITLE
Deprecated wp_get_sites  since 4.6.0

### ISSUE THREAD

**Issue by Chrico** [inpsyde/multilingual-press#236] opened 2016-10-11 06:25 UTC
#### Version Information
* WordPress: Version 4.6.1
* MultilingualPress: 2.4.7

#### Steps to Reproduce
1. Activate MLP with DEBUG-Settings to `TRUE`.
2. see the deprecated message:

![image](https://cloud.githubusercontent.com/assets/3417446/19260701/19370740-8f8c-11e6-8d73-d4d045e896a4.png)

#### What I Expected
No deprecated message ;-)

#### What Happened Instead
A deprecated message.

#### Where to find

`wp_get_sites()` is used in `MLP_Update_Plugin_Data` L58 and `uninstall.php` L66 and should be replaced with `get_sites()`.

**Comment by tfrommen** [comment] 2016-10-11 06:53
This is a duplicate of #229.

However, I will reconsider including this in a patch release now.

**Comment by tfrommen** [comment] 2016-10-11 07:14
Closed with https://github.com/inpsyde/multilingual-press/commit/e09c09bbcc835900d2e532c05755c72f58e142e5.

**Closed by tfrommen** 2016-10-11 07:14 UTC
Labels: enhancement, installation, refactoring
