### ISSUE TITLE
301 redirect on language menu in the default language website

### ISSUE THREAD

**Issue by natoinet** [inpsyde/multilingual-press#196] opened 2016-03-17 19:34 UTC
#### Version Information
* WordPress: 4.4.2
* MultilingualPress: 2.3.2

#### What Happens
On the default language website -say www.example.co.uk-, language links in the menu do not point directly to others domains (say www.example.fr & www.example.es):
```
<a rel="alternate" hreflang="fr-FR" href="http://www.example.co.uk/?noredirect=fr_FR"></a>
<a rel="alternate" hreflang="es-ES" href="http://www.example.co.uk/?noredirect=es_ES"></a>
```
And when clicking on those links, it goes through a 301 redirect:
http://www.example.co.uk/?noredirect=fr_FR redirects to http://www.example.fr/?noredirect=fr_FR
http://www.example.co.uk/?noredirect=es_ES redirects to http://www.example.es/?noredirect=es_ES

#### What I Expected
For SEO, direct links to other domains without redirect would be much better:
```
<a rel="alternate" hreflang="fr-FR" href="http://www.example.fr/"></a>
<a rel="alternate" hreflang="fr-FR" href="http://www.example.es/"></a>
```

How can I do that?

Thanks!

**Comment by tfrommen** [comment] 2016-03-18 08:11
Hi,

are you talking about _Language_ nav menu items provided by MultilingualPress?

URLs like `http://www.example.co.uk/?noredirect=fr_FR` should not be generated at all. The domain should match the language included in the `noredirect` parameter, so `http://www.example.fr/?noredirect=fr_FR` would be a valid URL.

The `noredirect` parameter is included to override the built-in [language negotiation](http://make.multilingualpress.pro/2014/03/language-negotiation-how-our-redirect-feature-works/). When a user intentionally wants to read content in a language that is not the _best match_, they should, of course, actually see the content - and not be redirected to the according translation in the best matching language (which is the current post anyway).

If you want to have _clean_ URLs, you can only achieve this by deactivating the _HTTP Redirect_ module on the MultilingualPress network settings page at `wp-admin/network/settings.php?page=mlp`.

However, the interesting (that is, **wrong**) part still is that such inconsistent URLs should not even occur.

Is there any additional information you can provide?

**Comment by tfrommen** [comment] 2016-04-11 09:58
@natoinet any news on this?

**Comment by hcortesb** [comment] 2016-04-19 14:26
Hi, 

I have the same problem. I'm using the _WordPress MU Domain Mapping_ to map to another domain. The problem is at the Language menu that shows the domains before the mapping and when I click in a different domaing, it does a 301 redirection to the mapped domain.

Thanks!

**Comment by tfrommen** [comment] 2016-04-22 07:12
@hcortesb please post this as new issue. Even though this is about redirects and menu, it's (most likely) about something different. Once you opened the new issue, I will delete both your and mine comment here. Thanks.

**Comment by tfrommen** [comment] 2016-06-09 06:12
No feedback here. I'm closing this, for now.

**Closed by tfrommen** 2016-06-09 06:12 UTC
Labels: bug, needs confirmation
