### ISSUE TITLE
Mlp_Content_Relations::set_relation does not update/invalidate internal cache

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#145] opened 2015-08-06 13:49 UTC
```Mlp_Content_Relations::get_relation()``` uses a cache to prevent multiple SQL queries to the same content relation. [See here](https://github.com/inpsyde/multilingual-press/blob/5a2620f94bcf2e67f0ffbabe11ca22627f5cd805/inc/db/Mlp_Content_Relations.php#L64-L66)

However if this exact relation is updated during a request, subsequent calls to ```Mlp_Content_Relations::get_relation()``` still receive the cached result, resulting in headaches among developers.

```Mlp_Content_Relations::set_relation()``` needs to update or invalidate that cache when it is used to update a relation

**Comment by kraftner** [comment] 2015-08-21 14:10
Just tested the branch for this issue, in my situation ( #151) the problem is solved.

**Comment by tfrommen** [comment] 2015-08-21 14:12
Thats' good. :) We're planning on using WordPress' built-in caching mechanisms, though. That's why this hasn't been merged into master.

**Comment by kraftner** [comment] 2015-08-21 14:16
Sounds reasonable, but it fixes it for now so I can continue working. Looking forward to your new solution.

**Comment by tfrommen** [comment] 2015-08-21 16:03
@kraftner does it still work with WordPress built-in caching? ;)

**Comment by kraftner** [comment] 2015-08-24 09:37
Sorry, I don't get what your ";)" refers to.

**Comment by tfrommen** [comment] 2015-08-24 09:38
@kraftner this issue's branch has been updated, however, I forgot the issue reference in the according commit. The caching functions have been replaced by WordPress built-in caching. And I was just asking if this is still working for you.

**Comment by kraftner** [comment] 2015-08-24 09:41
Thanks, now I get it. :smile:
I'll update and test later today and report back here.

**Comment by kraftner** [comment] 2015-08-24 10:20
No, sorry, seems to be broken.

I *think* the problem lies in [the casting of the cache to an array](https://github.com/inpsyde/multilingual-press/blob/bug/145_relations_cache/inc/db/Mlp_Content_Relations.php#L141).

If `wp_cache_get` returns false this turns it into `array(0=>false)` which then doesn't evaluate to `false` in the next line.

I think removing the casting works, but I haven't considered any unwanted side effects or why it is there in the first place.

**Comment by tfrommen** [comment] 2015-08-24 10:30
Thanks. That is, of course, right. Should be fixed now.

**Comment by kraftner** [comment] 2015-08-24 10:36
Yep, now it is working.
(I am not using a persistance cache, just for having mentioned that once)

**Comment by tfrommen** [comment] 2015-08-24 10:40
Closed with a5e8ed6ab74a44bf878eb9590c42c5111b03aa69.

**Closed by tfrommen** 2015-08-24 10:40 UTC
Labels: bug, content relations
