### ISSUE TITLE
Front lang ?

### ISSUE THREAD

**Issue by MaximeCulea** [inpsyde/multilingual-press#231] opened 2016-09-08 12:15 UTC
Hi,

Can I have some explaination about the front used locale lang ?

Why choose inpsyde_language for each site if in front the lang for locale is the WPLANG ? Do I am missing something ? 

I think a filter for front lang over locale to get the inpsyde one will be so usefull, no ?

Best

**Comment by tfrommen** [comment] 2016-09-08 12:19
Hi there,

I'm sorry but I don't follow.

Can you either describe in more detail what you expect when and where, and how the actual behavior differs from your expectations, or show the according code that you think is _wrong_?

Thanks,
Thorsten

**Comment by MaximeCulea** [comment] 2016-09-08 12:40
I can't understand why there is an option 'inpsyde_language' if in front the used lang is WPLANG.
That means inpsyde_language option is used only for the flag dropdown ?

I mean, if I set en_US or de_DE from the network option to a site, I am waiting that the returned locale is this value, instead WPLANG.
Infacto, by installing MLP, the inpsyde_option must be for the front whereas WPLANG for admin purpose, don't you agree ?

To manage this I have done this trick on filter "locale" : 
`/**
	 * Change on the fly the locale lang for front by using mlp one instead wplang
	 * 
	 * @param $locale
	 *
	 * @return mixed
	 * @author Maxime CULEA
	 */
	public function set_locale( $locale ) {
		if ( is_admin() ) {
			return $locale;
		}

		// Better use get_blog_meta lang for performance
		if ( function_exists( 'get_blog_meta' ) ) {
			$lang = get_blog_meta( get_current_blog_id(), 'lang', true );
			if ( ! empty( $lang ) ) {
				return $lang;
			}
		}

		// Get Inpsyde lang or local
		$langs = get_site_option( 'inpsyde_multilingual' );
		return empty( $langs[get_current_blog_id()]['lang'] ) ? $locale : $langs[get_current_blog_id()]['lang'];
	}`

**Comment by tfrommen** [comment] 2016-09-08 13:45
Firstly, there is no `inpsyde_language` option. There is the `inpsyde_multilingual` **site** option, though.

You have to differentiate between **WordPress language** and **MultilingualPress language**.
The former is used by WordPress - so it is the _system language_, if you want to call it that way. Both the backend UI is in this language, as well as anything else (back and front end) that runs through `gettext` (i.e., translation) functions.
The MultilingualPress language is the language that **your content** is presented in. Most of the time, these two languages (i.e., WordPress and MultilingualPress) are the same - but they don't have to be. The (main) reason for two distinct languages is that WordPress only is available in a limited amount of locales, while a user might want to present their content in a language that is not available. MultilingualPress, of course, provides a limited amount of languages, too. But you are free to edit them to your needs. So you can go ahead an edit an existing language to make it something else.

So, in general, use the same locale (or at least the same **language**) for WordPress and MultilingualPress, if possible.

If you want to have **only the WordPress Admin in a separate language**, then this is where the User Backend Language comes in handy. Please have a look [over here](http://slides.tfrommen.de/multilingualpress/#/9/1). This ia a JS-based presentation. Please use either the arrow controls, or arrow keys, or SPACE and SHIFT + SPACE to navigate. The _next_ slide is **down**. ;)

Also, you might want to have a look at the Trac tickets [#26511](https://core.trac.wordpress.org/ticket/26511) and [#29783](https://core.trac.wordpress.org/ticket/29783). If everything goes well, they will be included with WordPress 4.7.

Does this make sense?

**Comment by MaximeCulea** [comment] 2016-09-08 16:11
My bad, it's `inpsyde_multilingual` as I wrote into my snippet.

The confusion came, like you mention it, from the fact that `gettext` came along with the WPLANG lang, so I really can't understand why choose an other one from network to the same blog ? That's why I hooked `inpsyde_multilingual` lang for the current blog to locale. 

I already tried to play with the **WordPress Admin in a separate language** option, which had no effect :(

I have seen theses tickets, which inspired me for the snippet.

Thx for your explanations, if it's clear for you and other it's fine, I am surely missing something here .. :(

**Comment by tfrommen** [comment] 2016-09-20 06:11
Hi again!

> The confusion came, like you mention it, from the fact that `gettext` came along with the WPLANG lang...

Like I explained, the language set on _Options &rarr; General_ is the **system** language. So this is what WordPress has as internal reference - for anything it does - so `gettext` is, of course, part of this.

> ...I really can't understand why choose an other one from network to the same blog ?

Like mentioned before, in general, you wouldn't use different languages for WordPress and MultilingualPress. But it's possible - and one use case is that you want your content to be in a language that WordPress is not aware of. See #232, for example. Besides the fact that our language entry is unfortunately incorrect, the user wants their content to be in the Chinese spoken in the Singapore region. WordPress doesn't have a `zh_SG` locale, though. So what you would want/have to do is set WordPress to be just `Chinese` (which is China), but have MultilingualPress define the content language as __Chinese (Singapore)__ (which will give `zh_SG` for the `hreflang` attributes).

> I already tried to play with the **WordPress Admin in a separate language** option, which had no effect :(

What do you mean by this?
Did you set WordPress to be, say, English, and the MultilingualPress language to be, say, French, but your Backend (and the frontend template strings) were in French (which is wrong)?

> Thx for your explanations! If it's clear for your team and people using it, that's fine, cause I really have the feeling to miss something here .. :(

I hope I could make this a little clearer...? If not, ask again. :)

Best regards,
Thorsten

**Comment by MaximeCulea** [comment] 2016-09-20 07:29
Hi @tfrommen,
thx for your time!

I have a site which the backend had to be in English (`wplang`) for contributors and in French (`inpsyde_multilingual`) for visitors to set the french relation and flag.
The admin display was considering `wplang` but the front one too, which for a french guy isn't good because we sucks at english ! :D

So I had to hook on `get_locale` filter (! is_admin) to change it with the selected `inpsyde_multilingual` lang, french for me. This affected the gettext which allowed me to display the front in french, in fact like the flag and the relation for this site.

Now considering this I wonder why I need to do this little trick ? Is `inpsyde_multilingual` option just setting the flag for a blog, nothing else, if not filtering the get_locale for gettext purpose?

So two solution :
- my total incomprehension by the use of this option?
- a little bug with the `inpsyde_multilingual` option?

Best

**Comment by tfrommen** [comment] 2016-09-21 08:14
Hi!

> I have a site which the backend had to be in English (`wplang`) for contributors and in French (`inpsyde_multilingual`) for visitors to set the french relation and flag.

This is not how this works. Both the back end and the front end is using the WordPress locale for anything language-specific (like running strings through `gettext`). The MultilingualPress language is only used to indicate the language of the **content**.

> The admin display was considering `wplang` but the front one too, which for a french guy isn't good because we sucks at english ! :D

In order to see the backend in any other available language, you should use the _User Backend Language_ feature.
Go to the MultilingualPress settings page in the Network Admin (`~/wp-admin/network/settings.php?page=mlp`), and check if _User Backend Language_ is activated (i..e, the checkbox is ticked). If not, tick the checkbox, and save the change.
Then edit your site to have the language that is should have in the first place. Meaning, if you have French content, then the site should have both the WordPress locale (_Options &rarr; General_ on the site itself) and the MultilingualPress language (on the _Edit Site_ page, _MultilingualPress_ tab, in the Network Admin).
After this, anyone, who wants to see the back end in another language (e.g., English), just has to go to their personal profile and choose their desired back-end language.

Does this make sense (to you)?

Best regards,
Thorsten

**Comment by MaximeCulea** [comment] 2016-09-21 08:21
Hi,
100% agree, but that was the point : `User Backend Language` mlp option had no effect on my sites. 

> "I already tried to play with the WordPress Admin in a separate language option, which had no effect :("

That's why I had to make this trick :p

**Comment by tfrommen** [comment] 2016-09-21 08:25
So, are you saying you set your site language to be _French_, selected _English_ as your personal _User Backend Language_ (on `~/wp-admin/profile.php`), save the setting, and still your WordPress Admin is displayed in French?

If so, then this is either a bug, or something else is interfering here.

Also, why did you close this issue? :)

**Comment by MaximeCulea** [comment] 2016-09-21 08:49
Hum, because it seems to be a misunderstanding (only with me) more than something else. 
Because I explained my issue and can't do more about it and moreover pasted the code that corrected my issue.
I also don't have a lot of time to accord to this, so apologize me if I close this issue.

To answer you, yes my site was set in english, my personal language in french, and the front `inpsyde_multilingual` to french. So the BO was in french and the front in english.

**Comment by tfrommen** [comment] 2016-09-21 08:56
If the issue is solved for you, then you are, of course, free to close this. :)
I just understood it that way that you have been using the _User Backend Language_ and it didn't work as expected/designed.

To sum it up:

* in general, have the WordPress language set to what the content is given in;
* have the MultilingualPress language set to the same value;
* if your content is in a language that does not (yet) exist in WordPress (e.g., _Chinese (Singapore)_), then choose the _next best_ language for WordPress (in this case _Chinese_), and have the MultilingualPress language be the exact thing that you want it to be (this might include that you have to edit an existing language to be like you want/need it - because maybe even MultilingualPress doesn't have the language right now);
* if you want to see the Admin UI in a different language, use the _User Backend Language_.

If all this doesn't work, ... something is wrong. :confused:

**Closed** 2016-11-02 12:02 UTC
Labels: discussion, language manager, support, user backend language
