### ISSUE TITLE
Prevent users from changing translations if they lack the capabilities for the remote blog

### ISSUE THREAD

**Issue by Biont** [inpsyde/multilingual-press#116] opened 2015-06-10 16:25 UTC
Writers/Translators of a site may (and will) be spread out across multiple countries.
Right now, as long as a user can 'edit_posts' on his own site, he can also change the content of any other translation of that post.

This can lead to accidental deletions and confusion. And of course, a user simply should not be able edit a post's contents when he actually lacks the capabilities to do so.

The easy solution would be to simply not add the translation metaboxes in the first place, which can be done by adding a check for ```current_user_can_for_blog( $blog_id, 'edit_posts'  )``` to [```Mlp_Translation_Metabox ::register_meta_boxes()```](https://github.com/inpsyde/multilingual-press/blob/36d312c80c053e4932282df401cd2a776d285511/inc/post-translator/Mlp_Translation_Metabox.php#L131)

I am not aware of the implications that this change would have on post saving & syncing, but everything seemed to work after a quick test with an editor/subscriber setup and 2 languages.

Is there a reason why this is not the default behaviour?

**Comment by tfrommen** [comment] 2015-06-10 16:29
FYI: This is a duplicate of an issue on the (private) PRO repository.

**Comment by Biont** [comment] 2015-06-12 08:03
Th current implementaton is a bit lacking: Hardcoding a single capability may prove to be not flexible enough. A more thorough approach will be created in a separate branch. I will revert the changes made in the meantime

**Comment by tfrommen** [comment] 2015-06-29 11:30
Closed with ac3ea73356f182af4f56ee009ae7ee81f599598d.

**Closed by tfrommen** 2015-06-29 11:30 UTC
Labels: bug
